version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers

    step:
      - checkout

      - run: # install and activate virtual environment with pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - run: # run tests
          command: |
            . venv/bin/activate
            #python manage.py test